FROM mysql:8.0

RUN apt-get update && apt-get -y install locales-all

ENV LANG ja_JP.UTF-8
ENV LANGUAGE ja_JP:ja
ENV LC_ALL ja_JP.UTF-8
ENV MYSQL_DATABASE craft
ENV MYSQL_USER craft
ENV MYSQL_PASSWORD craft
ENV MYSQL_ROOT_PASSWORD craft
ENV TZ 'Asia/Tokyo'
